### ISSUE TITLE
Helm repo address

### ISSUE THREAD

**Issue by glitchcrab** [sergelogvinov/proxmox-cloud-controller-manager#107]
I've been through the repo multiple times but I'm struggling to understand how I can use this image. I did manage to get it running with `helm install proxmox-cloud-controller-manager oci://ghcr.io/sergelogvinov/charts/proxmox-cloud-controller-manager`, however when I try and install the chart with Fluxcd I cannot find a combination of OCI repo and chart name which works. I see a lot of this happening:

```
HelmChart 'kube-system/kube-system-proxmox-cloud-controller-manager' is not ready: chart pull error: failed to download chart for remote reference: failed to get 'oci://ghcr.io/sergelogvinov/charts/proxmox-cloud-controller-manager/proxmox-cloud-controller-manager:v0.4.0': failed to authorize: failed to fetch anonymous token: unexpected status from GET request to https://ghcr.io/token?scope=repository%!!(MISSING)!(MISSING)A(MISSING)sergelogvinov%!!(MISSING)!(MISSING)F(MISSING)charts%!!(MISSING)!(MISSING)F(MISSING)proxmox-cloud-controller-manager%!!(MISSING)!(MISSING)F(MISSING)proxmox-cloud-controller-manager%!!(MISSING)!(MISSING)A(MISSING)pull&service=ghcr.io: 403 Forbidden
```

The [helm install](https://github.com/sergelogvinov/proxmox-cloud-controller-manager?tab=readme-ov-file#method-2-helm-chart) command in the readme doesn't explain where the chart is stored - does it exist in a standard https helm repo or is it only accessible as an OCI artifact?

**Comment by glitchcrab** [comment]
OK, for anyone who may be interested, I did finally manage to get this to work with the following manifests:

```
kind: HelmRepository
apiVersion: source.toolkit.fluxcd.io/v1beta2
metadata:
  name: proxmox-cloud-controller-manager
  namespace: kube-system
spec:
  interval: 5m0s
  type: "oci"
  url: oci://ghcr.io/sergelogvinov/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: proxmox-cloud-controller-manager
  namespace: kube-system
spec:
  releaseName: proxmox-cloud-controller-manager
  chart:
    spec:
      chart: proxmox-cloud-controller-manager
      sourceRef:
        kind: HelmRepository
        name: proxmox-cloud-controller-manager
        namespace: kube-system
      version: "0.2.0"
```
