### ISSUE TITLE
Allow a root CA to be passed as part of the cluster config

### ISSUE THREAD

**Issue by tamcore** [sergelogvinov/proxmox-cloud-controller-manager#65]
### Description

Alternatively to setting `insecure: true` it would be nice, if we could pass a custom CA as part of the cluster configuration.

Maybe something in the format of
```yaml
clusters:
  - url: https://cluster-api-1.exmple.com:8006/api2/json
    token_id: "user!token-id"
    token_secret: "secret"
    region: cluster-1
    ca: |
      -----BEGIN CERTIFICATE-----
      ...redacted for brevity
      MIIkzCCA3ugAwIBAgIUHCbAHZn90lhjRy+252KGWYOo4cgwDQYJKoZIhvcNAQEL
      ...redacted for brevity
      -----END CERTIFICATE-----      
```
